version: "3.9"

services:
  frontend:
    build: ./wallpaper-wall
    container_name: wallpaper-frontend
    ports:
      - "80:80"
    restart: always

  backend:
    build: ./backend
    container_name: wallpaper-backend
    ports:
      - "8000:8000"
    restart: always
