version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    container_name: wallpaper-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/static:/app/static
    restart: always

  frontend:
    build:
      context: .
      dockerfile: wallpaper-wall/dockerfile
    container_name: wallpaper-frontend
    ports:
      - "80:80"
    restart: always

