# backend/Dockerfile
FROM python:3.11-slim

WORKDIR /app

# 复制依赖文件
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt

# 复制整个 backend 文件夹
COPY backend/ /app/

# 对外暴露端口
EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

